package be.elevenways.hohenheim.server.instance;

import be.elevenways.hohenheim.model.DatabaseModel;
import be.elevenways.hohenheim.model.InstanceModel;
import be.elevenways.hohenheim.model.InstanceTemplateModel;
import be.elevenways.hohenheim.test.HohenheimTestRuntime;
import be.elevenways.zenit.common.orm.datasource.Row;
import be.elevenways.zenit.common.orm.model.Model;
import be.elevenways.zenit.common.orm.model.Models;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * New template labels use the core fold, while already stored database names and captured aliases stay identifiers.
 *
 * @author Jelle De Loecker
 * @since 0.1.0
 */
class TemplateSlugIdentityTest {

    @BeforeAll
    static void boot() {
        HohenheimTestRuntime.ensureBooted();
    }

    @Test
    void canonicalNewLabelsKeepTheStoredIdentityCasesByteIdentical() {
        // 1. These existing ASCII label cases keep their exact spelling, including the product's length ceiling.
        assertThat(TemplateDatabases.labelFor("Diax Live WordPress", "WORDPRESS_DB"))
            .as("step 1: the existing WordPress label stays byte-identical")
            .isEqualTo("diax-live-wordpress-wordpress-db");
        assertThat(TemplateDatabases.labelFor("a-very-long-instance-name-that-goes-on", "DB"))
            .as("step 1: the existing truncated label stays byte-identical")
            .isEqualTo("a-very-long-instance-name-tha-db");
        assertThat(TemplateDatabases.labelFor("***", "DB"))
            .as("step 1: the empty-fold fallback stays byte-identical").isEqualTo("db-db");

        // 2. New Latin diacritics fold at the one home instead of disappearing from two private regex copies.
        assertThat(TemplateDatabases.labelFor("Café Über", "DB"))
            .as("step 2: a newly derived database label uses the core fold").isEqualTo("cafe-uber-db");
        Row source = new Row();
        source.set(InstanceModel.NAME, "Café Über");
        assertThat(InstanceTemplateCapture.aliasFor(source))
            .as("step 2: a newly captured alias uses the same fold").matches("tpl-cafe-uber-\\d{8}-\\d{6}");
        source.set(InstanceModel.NAME, "Capture ME");
        assertThat(InstanceTemplateCapture.aliasFor(source))
            .as("step 2: the existing ASCII capture case keeps its spelling")
            .matches("tpl-capture-me-\\d{8}-\\d{6}");
        source.set(InstanceModel.NAME, "***");
        assertThat(InstanceTemplateCapture.aliasFor(source))
            .as("step 2: the existing capture fallback keeps its spelling")
            .matches("tpl-instance-\\d{8}-\\d{6}");

        // 3. A captured alias persisted before the fold change is never regenerated by editing its template.
        String legacyAlias = "tpl-caf-20260703-120000";
        Model templates = Models.get(InstanceTemplateModel.class);
        Row template = templates.createEmptyRow();
        template.set(InstanceTemplateModel.NAME, "Legacy Café capture");
        template.set(InstanceTemplateModel.KIND, "hohenheim:workspace");
        template.set(InstanceTemplateModel.SETTINGS, Map.of("image", legacyAlias, "image_origin", "prepared"));
        templates.save(template);
        template.set(InstanceTemplateModel.DESCRIPTION, "An edited description");
        templates.save(template);
        Map<?, ?> settings = (Map<?, ?>) templates.findById(template.get(InstanceTemplateModel.ID))
            .get(InstanceTemplateModel.SETTINGS);
        assertThat(((String) settings.get("image")).getBytes(StandardCharsets.UTF_8))
            .as("step 3: the stored daemon alias stays byte-identical")
            .containsExactly(legacyAlias.getBytes(StandardCharsets.UTF_8));

        // 4. Existing database labels are stored identity too, so an unrelated edit preserves the old fold's bytes.
        String legacyLabel = "caf-db";
        Model databases = Models.get(DatabaseModel.class);
        Row database = databases.createEmptyRow();
        database.set(DatabaseModel.NAME, legacyLabel);
        database.set(DatabaseModel.ENGINE, "postgres");
        database.set(DatabaseModel.DB_NAME, "legacy_caf");
        database.set(DatabaseModel.DB_USER, "legacy_caf");
        databases.save(database);
        database.set(DatabaseModel.STATUS, DatabaseModel.STATUS_ACTIVE);
        databases.save(database);
        assertThat(databases.findById(database.get(DatabaseModel.ID)).get(DatabaseModel.NAME)
                .getBytes(StandardCharsets.UTF_8))
            .as("step 4: the stored database label stays byte-identical")
            .containsExactly(legacyLabel.getBytes(StandardCharsets.UTF_8));
    }
}
