package be.elevenways.hohenheim.server.game;

import org.checkerframework.checker.nullness.qual.NonNull;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders the generated Velocity proxy configuration (velocity.toml) from the enabled
 * game-domain mappings of one proxy instance.
 *
 * AIDEV-NOTE: the file is generated WHOLLY -- servers, try order and forced-hosts are all
 * derived from mappings, so there is exactly one source of truth and reconciliation is a
 * full re-render, never a patch. The forwarding secret deliberately does NOT appear here:
 * it rides the separate forwarding.secret template file ({@code {{FORWARDING_SECRET}}}),
 * so this rendered content is safe to persist and diff. Backend addresses use the Docker
 * container NAME on the shared link network (user-defined networks resolve member names).
 */
public final class VelocityConfigs {

    /** Container path of the generated proxy config (the image's workdir is /data). */
    public static final String CONFIG_PATH = "/data/velocity.toml";

    /** Default Velocity listen port when the proxy's settings declare none. */
    public static final int DEFAULT_BIND_PORT = 25577;

    private VelocityConfigs() {
    }

    /**
     * One mapping's contribution: a forced host aimed at one backend.
     *
     * @param hostname       canonical exact hostname (the forced-hosts key)
     * @param backendId      backend instance id (names the server entry)
     * @param backendHandle  backend container name, resolvable on the link network
     * @param backendPort    game port INSIDE the backend container
     */
    public record Entry(@NonNull String hostname, int backendId,
                        @NonNull String backendHandle, int backendPort) {
    }

    /** Render the full velocity.toml for the given mappings. */
    public static @NonNull String render(int bindPort, @NonNull List<Entry> entries) {
        Map<String, String> servers = new LinkedHashMap<>();
        Map<String, List<String>> forcedHosts = new LinkedHashMap<>();
        for (Entry entry : entries) {
            String serverName = "backend-" + entry.backendId();
            servers.put(serverName, entry.backendHandle() + ":" + entry.backendPort());
            forcedHosts.computeIfAbsent(entry.hostname(), key -> new ArrayList<>())
                .add(serverName);
        }

        StringBuilder toml = new StringBuilder();
        toml.append("# Generated by hohenheim (game-domains). Manual edits are overwritten\n");
        toml.append("# on every mapping change; edit the mappings instead.\n");
        toml.append("config-version = \"2.6\"\n");
        toml.append("bind = \"0.0.0.0:").append(bindPort).append("\"\n");
        toml.append("motd = \"A hohenheim-managed Velocity proxy\"\n");
        toml.append("online-mode = true\n");
        toml.append("player-info-forwarding-mode = \"modern\"\n");
        toml.append("forwarding-secret-file = \"forwarding.secret\"\n");
        toml.append("\n[servers]\n");
        for (Map.Entry<String, String> server : servers.entrySet()) {
            toml.append(server.getKey()).append(" = \"").append(server.getValue())
                .append("\"\n");
        }
        toml.append("try = [");
        toml.append(String.join(", ",
            servers.keySet().stream().map(name -> "\"" + name + "\"").toList()));
        toml.append("]\n");
        toml.append("\n[forced-hosts]\n");
        for (Map.Entry<String, List<String>> host : forcedHosts.entrySet()) {
            toml.append("\"").append(host.getKey()).append("\" = [");
            toml.append(String.join(", ",
                host.getValue().stream().map(name -> "\"" + name + "\"").toList()));
            toml.append("]\n");
        }
        toml.append("\n[advanced]\n");
        return toml.toString();
    }
}
